# Generated by Django 4.2 on 2023-04-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("djstripe", "0011_2_7"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUniqueSellingPointThroughModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
            ],
            options={
                "ordering": ("product_util", "order"),
            },
        ),
        migrations.CreateModel(
            name="UniqueSellingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=128)),
                ("description_en", models.CharField(max_length=128, null=True)),
                ("description_nl", models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductUtil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djstripe.product",
                    ),
                ),
                (
                    "unique_selling_points",
                    models.ManyToManyField(
                        through="qt_billing.ProductUniqueSellingPointThroughModel",
                        to="qt_billing.uniquesellingpoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productuniquesellingpointthroughmodel",
            name="product_util",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qt_billing.productutil"
            ),
        ),
        migrations.AddField(
            model_name="productuniquesellingpointthroughmodel",
            name="unique_selling_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qt_billing.uniquesellingpoint",
            ),
        ),
    ]
