# Generated by Django 4.2.1 on 2023-05-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productutil",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
