# Generated by Django 4.2.1 on 2023-07-04 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_security", "0003_device_user_alter_device_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="family",
            new_name="info",
        ),
        migrations.RemoveField(
            model_name="device",
            name="name",
        ),
        migrations.RemoveField(
            model_name="device",
            name="os",
        ),
    ]
