# Generated by Django 4.2.1 on 2023-07-05 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_security", "0007_device_user_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="user_agent",
        ),
    ]
