# Generated by Django 4.2.1 on 2023-07-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qt_security", "0008_remove_device_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qt_security.deviceimage",
            ),
        ),
    ]
