# Generated by Django 4.2 on 2023-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="are_guidelines_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_subscription_paid",
            field=models.BooleanField(default=False),
        ),
    ]
