# Generated by Django 4.2 on 2023-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0003_remove_user_is_subscription_paid_user_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("R", "Registered"),
                    ("V", "Verified"),
                    ("S", "Subscribed"),
                    ("U", "Unsubscribed"),
                ],
                default="R",
                editable=False,
                max_length=2,
            ),
        ),
    ]
