# Generated by Django 4.2 on 2023-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0004_user_account_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription",
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
