# Generated by Django 4.2 on 2023-04-25 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0005_remove_user_subscription_user_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
