# Generated by Django 4.2 on 2023-04-28 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0007_newslettersubscriber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newslettersubscriber",
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newletter Subscribers",
            },
        ),
    ]
