# Generated by Django 4.2 on 2023-05-01 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0008_alter_newslettersubscriber_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsletterSubscriber",
        ),
    ]
