# Generated by Django 4.2 on 2023-05-12 09:18

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0010_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("Registered", "Registered"),
                    ("Verified", "Verified"),
                    ("Subscribed", "Subscribed"),
                    ("U", "Unsubscribed"),
                    ("Password Reset", "Password Reset"),
                    ("Change Email", "Change Email"),
                ],
                default="Registered",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("Registered", "Registered"),
                    ("Verified", "Verified"),
                    ("Subscribed", "Subscribed"),
                    ("U", "Unsubscribed"),
                    ("Password Reset", "Password Reset"),
                    ("Change Email", "Change Email"),
                ],
                default="Registered",
                max_length=50,
            ),
        ),
    ]
