# Generated by Django 4.2 on 2023-05-12 09:19

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0011_alter_user_account_status_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("rerified", "Verified"),
                    ("subscribed", "Subscribed"),
                    ("unsubscribed", "Unsubscribed"),
                    ("password_reset", "Password Reset"),
                    ("change_email", "Change Email"),
                ],
                default="registered",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("registered", "Registered"),
                    ("rerified", "Verified"),
                    ("subscribed", "Subscribed"),
                    ("unsubscribed", "Unsubscribed"),
                    ("password_reset", "Password Reset"),
                    ("change_email", "Change Email"),
                ],
                default="registered",
                max_length=50,
            ),
        ),
    ]
