# Generated by Django 4.2 on 2023-05-12 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0012_alter_user_account_status_alter_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_status",
        ),
    ]
