# Generated by Django 4.2 on 2023-05-12 09:40

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0013_remove_user_account_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=django_fsm.FSMField(default="registered", max_length=50),
        ),
    ]
