# Generated by Django 4.2 on 2023-05-12 14:45

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0015_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("registered", "Registered"),
                    ("verified", "Verified"),
                    ("subscribed", "Subscribed"),
                    ("unsubscribed", "Unsubscribed"),
                    ("password_reset", "Password Reset"),
                    ("change_email", "Change Email"),
                ],
                default="registered",
                max_length=50,
            ),
        ),
    ]
