# Generated by Django 4.2.1 on 2023-06-22 07:18

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0017_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("registered", "Registered"),
                    ("verified", "Verified"),
                    ("subscribed", "Subscribed"),
                ],
                default="registered",
                max_length=50,
            ),
        ),
    ]
