# Generated by Django 4.2.1 on 2023-07-07 07:06

from django.db import migrations, models
import qt_utils.helpers
import qt_utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0019_alter_user_customer_alter_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=250,
                null=True,
                storage=qt_utils.models.QTPrivateAssets(),
                upload_to=qt_utils.helpers.aws_instance_directory_path,
            ),
        ),
    ]
