# Generated by Django 4.2.1 on 2023-07-10 10:31

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ("qt_auth", "0020_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("registered", "Registered"),
                    ("verified", "Verified"),
                    ("change_email", "Change Email"),
                ],
                default="registered",
                max_length=50,
            ),
        ),
    ]
