# Generated by Django 4.2.1 on 2023-08-18 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import qt_utils.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(choices=[("degiro", "DEGIRO")], max_length=128),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=250,
                        null=True,
                        storage=qt_utils.models.QTPublicAssets(),
                        upload_to="images/broker-information/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrokerAuthenticationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("username and password", "USERNAME_PASSWORD"),
                            ("email and password", "EMAIL_PASSWORD"),
                        ],
                        max_length=128,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrokerPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                (
                    "int_account",
                    encrypted_model_fields.fields.EncryptedIntegerField(
                        blank=True, null=True
                    ),
                ),
                (
                    "authentication_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_portfolios",
                        to="qt_brokers.brokerauthenticationmethod",
                    ),
                ),
                (
                    "broker_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_portfolios",
                        to="qt_brokers.broker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("internal_id", models.CharField(max_length=255)),
                ("isin", models.CharField(max_length=128)),
                ("company", models.CharField(max_length=255)),
                ("ticker", models.CharField(max_length=128)),
                ("ticker_suffix", models.CharField(max_length=128)),
                (
                    "exchange_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "exchange_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "exchange_city",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "exchange_country",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("currency", models.CharField(max_length=5)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="qt_brokers.brokerportfolio",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="broker",
            name="authentication_methods",
            field=models.ManyToManyField(
                related_name="brokers", to="qt_brokers.brokerauthenticationmethod"
            ),
        ),
        migrations.AddConstraint(
            model_name="broker",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_broker"),
        ),
    ]
