# Generated by Django 4.2.1 on 2023-08-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qt_brokers", "0002_rename_brokerportfolio_brokeraccount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holding",
            old_name="portfolio",
            new_name="account",
        ),
        migrations.AlterField(
            model_name="brokeraccount",
            name="authentication_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_accounts",
                to="qt_brokers.brokerauthenticationmethod",
            ),
        ),
        migrations.AlterField(
            model_name="brokeraccount",
            name="broker_information",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_account",
                to="qt_brokers.broker",
            ),
        ),
    ]
