# Generated by Django 4.2.1 on 2023-08-19 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_brokers", "0003_rename_portfolio_holding_account_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brokeraccount",
            old_name="broker_information",
            new_name="broker",
        ),
    ]
