# Generated by Django 4.2.1 on 2023-08-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qt_brokers", "0004_rename_broker_information_brokeraccount_broker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokeraccount",
            name="authentication_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authentication_method",
                to="qt_brokers.brokerauthenticationmethod",
            ),
        ),
    ]
