# Generated by Django 4.2.1 on 2023-08-20 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qt_brokers", "0005_alter_brokeraccount_authentication_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokeraccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
