# Generated by Django 4.2.1 on 2023-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_brokers", "0006_alter_brokeraccount_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeraccount",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
    ]
