# Generated by Django 4.2.1 on 2023-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_brokers", "0009_remove_brokeraccount_unique_broker_account_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="brokeraccount",
            name="unique_broker_username_account",
        ),
        migrations.RemoveConstraint(
            model_name="brokeraccount",
            name="unique_broker_email_account",
        ),
        migrations.AddConstraint(
            model_name="brokeraccount",
            constraint=models.UniqueConstraint(
                fields=("broker", "authentication_method", "username"),
                name="unique_broker_username_account",
            ),
        ),
    ]
