# Generated by Django 4.2.1 on 2023-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "qt_brokers",
            "0011_remove_brokeraccount_unique_broker_username_account_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokeraccount",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
