# Generated by Django 4.2.1 on 2023-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_brokers", "0012_alter_brokeraccount_username"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="brokeraccount",
            name="unique_broker_username_account",
        ),
        migrations.RemoveConstraint(
            model_name="brokeraccount",
            name="unique_broker_email_account",
        ),
        migrations.AddConstraint(
            model_name="brokeraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("username__isnull", False)),
                fields=("broker", "authentication_method", "username"),
                name="unique_broker_account_username",
            ),
        ),
        migrations.AddConstraint(
            model_name="brokeraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("broker", "authentication_method", "email"),
                name="unique_broker_account_emailt",
            ),
        ),
    ]
