# Generated by Django 4.2 on 2023-05-11 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_utils", "0002_newslettersubscriber_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newslettersubscriber",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="newslettersubscriber",
            old_name="updated_at",
            new_name="updated",
        ),
    ]
