# Generated by Django 4.2.1 on 2023-06-22 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qt_utils", "0003_rename_created_at_newslettersubscriber_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newslettersubscriber",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="newslettersubscriber",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
