# Generated by Django 4.2.1 on 2023-06-26 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qt_utils", "0004_rename_created_newslettersubscriber_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedJWTToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=1024, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
